// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpLjQ2n2CriOf7v0BpF4tnWCq-zBG2I28',
    appId: '1:210500312465:web:101f8d4bfbc79f9b494e30',
    messagingSenderId: '210500312465',
    projectId: 'barber-app-7b11c',
    authDomain: 'barber-app-7b11c.firebaseapp.com',
    storageBucket: 'barber-app-7b11c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-YVTTBZZWEXGpr-V5G3YCIvt515tqrxQ',
    appId: '1:210500312465:android:5759a361b1483ae3494e30',
    messagingSenderId: '210500312465',
    projectId: 'barber-app-7b11c',
    storageBucket: 'barber-app-7b11c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzdeM1SPMP3sIl5g9tk-1vQZNCg1fcSpk',
    appId: '1:210500312465:ios:b7d9c0501bef06e9494e30',
    messagingSenderId: '210500312465',
    projectId: 'barber-app-7b11c',
    storageBucket: 'barber-app-7b11c.firebasestorage.app',
    iosBundleId: 'com.example.taobook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzdeM1SPMP3sIl5g9tk-1vQZNCg1fcSpk',
    appId: '1:210500312465:ios:b7d9c0501bef06e9494e30',
    messagingSenderId: '210500312465',
    projectId: 'barber-app-7b11c',
    storageBucket: 'barber-app-7b11c.firebasestorage.app',
    iosBundleId: 'com.example.taobook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpLjQ2n2CriOf7v0BpF4tnWCq-zBG2I28',
    appId: '1:210500312465:web:6970ae98e69b1c60494e30',
    messagingSenderId: '210500312465',
    projectId: 'barber-app-7b11c',
    authDomain: 'barber-app-7b11c.firebaseapp.com',
    storageBucket: 'barber-app-7b11c.firebasestorage.app',
  );
}
